### ISSUE TITLE
Linking to Poppler dylib differently

### ISSUE THREAD

**Issue by luzpaz** [vslavik/diff-pdf#35]
Each time Poppler is updated and added to Homebrew Package Manager there is a need initiate a rebuild for diff-pdf in order to relink to the right updated poppler library. See as examples:  
* https://github.com/Homebrew/homebrew/pull/44238 
* https://github.com/Homebrew/homebrew/pull/45244
* https://github.com/Homebrew/homebrew/pull/46768
* and now https://github.com/Homebrew/homebrew/pull/47114  

Is there a way to make this more seamless ?

**Comment by vslavik** [comment]
Congratulations, you made the first step on the path to understanding how shared libraries work! The next step should be to read some docs to grasp what a silly idea it is to somehow magically (sorry, “differently”) link things so that that symbols, ABIs or sonames don’t play a role.

This project has absolutely nothing to do with Homebrew (and *obviously* so), nor with Poppler, and your Homebrew problems have absolutely nothing to do with this project. That’s just home Homebrew is “designed”. Go complain to them or use a proper package manager — they all solved this particular problem years before Homebrew was even born.

**Comment by luzpaz** [comment]
Ok, was not expecting that response. Thanks anyway.
