### ISSUE TITLE
Trojan.Zmutzy.803 

### ISSUE THREAD

**Issue by phelanx** [vslavik/diff-pdf#51]
While I can't confirm it, I'm not going to risk it. Your download appears to be a trojan according to a few virus scanners. See the following link.

https://www.virustotal.com/en/file/cf56b5b8245dc1e6f158b0f95092d152a6d53600fdd61cb30b49e0ef0a9948ab/analysis/1490276064/

**Comment by vslavik** [comment]
> While I can't confirm it, I'm not going to risk it.

Yeah, let’s fearmonger instead of actually doing something useful or using some *\*gasp\** facts.

Don’t be ridiculous. This offensive and unfounded accusation of yours has no basis in reality. Please complain to your crappy AV vendor instead. BitDefender in particular has a reputation for being one of the crappiest in the whole industry (which is far from being a paragon of quality to begin with).

**Comment by phelanx** [comment]
@vslavik - You've spent a lot of time on what is likely a quality tool, and I apologize for the unintentional "fearmongering" and offensive tone. That certainly was not my objective. I'll edit my original comment.

Unfortunately, the _results_ are founded in reality and are facts. Anti-virus software _did_ flag the download as a malware. The _validity_ of those results is another story and not easily confirmed.

**Comment by vslavik** [comment]
Of course the validity is confirmed easily enough. You have all the data at your disposal. But it’s work, yes.

In any case there’s nothing that \*I\* can do about false positives of some products (or product; this would seem to be outsourced, hence the same misclassification not shared by other AV) that I have no control over — particularly when they are well aware of their own lack of quality and don’t even have easily found false positive reporting page. (Yes, I really can’t stand BitDefender, they’re a pain to deal with and constantly make bogus reports and take weeks to fix them.)

Presumably you’re a customer, otherwise how would you encounter this. So it’s *you* who should complain to them about the quality of their product. 

I would also strongly recommend not installing or using any such crap — use Windows Defender, which unlike pretty much everything else is actually a good, responsibly developed, protection layer.

Finally, if you don’t trust the binaries, compile from source code. If you don’t trust the source code either, review it.
